FROM golang:1.24.4-alpine3.22

RUN apk add --no-cache bash gcc inotify-tools musl-dev psmisc

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

RUN go install github.com/go-delve/delve/cmd/dlv@latest

#RUN addgroup -g 1001 -S gorque && \
#    adduser -u 1001 -S gorque -G gorque

WORKDIR /go/src/gorque/backend

COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY ./startScript.sh /

RUN go build -gcflags "all=-N -l" -v -o /gorque-backend .

#RUN chown -R gorque:gorque /go/src/gorque/backend && \
#    chmod +x /startScript.sh

#USER gorque

EXPOSE 8080 40000

ENTRYPOINT ["bash",  "/startScript.sh"]
