name: Build and push Docker images

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -f backend/Dockerfile.prod -t ghcr.io/${{ github.repository }}-backend:latest ./backend
        docker push ghcr.io/${{ github.repository }}-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -f frontend/Dockerfile.prod -t ghcr.io/${{ github.repository }}-frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository }}-frontend:latest
